class Constants {
  static const Map<String, List<Map<String, dynamic>>> allTypes = {
    "Data Science Fundamentals": [
      {
        'id': 'ds_intro',
        'title': 'Introduction to Data Science',
        'tier': 'free',
        'topics': [
          "What is Data Science",
          "Data Science Process",
          "Applications",
          "Tools Ecosystem",
          "Team Roles",
        ],
      },
      {
        'id': 'data_lifecycle',
        'title': 'Data Science Lifecycle',
        'tier': 'free',
        'topics': [
          "Data Collection",
          "Data Preparation",
          "Exploratory Analysis",
          "Model Building",
          "Deployment",
          "Monitoring",
        ],
      },
      {
        'id': 'prblm_formltn',
        'title': 'Problem Formulation',
        'tier': 'free',
        'topics': [
          "Business Understanding",
          "Problem Definition",
          "Success Metrics",
          "Stakeholder Management",
        ],
      },
      {
        'id': 'ethics',
        'title': 'Data Ethics and Privacy',
        'tier': 'vip',
        'topics': [
          "Data Privacy Laws",
          "Ethical Considerations",
          "Bias in AI",
          "Transparency",
          "Accountability",
        ],
      },
      {
        'id': 'career',
        'title': 'Data Science Career Paths',
        'tier': 'vip',
        'topics': [
          "Data Scientist Roles",
          "Data Analyst Roles",
          "Skills Required",
          "Industry Demand",
          "Career Growth",
        ],
      },
    ],
    "Statistics & Mathematics": [
      {
        'id': 'stats_basics',
        'title': 'Basic Statistics',
        'tier': 'free',
        'topics': [
          "Descriptive Statistics",
          "Measures of Central Tendency",
          "Measures of Dispersion",
          "Distributions",
          "Correlation",
        ],
      },
      {
        'id': 'probability',
        'title': 'Probability Theory',
        'tier': 'free',
        'topics': [
          "Probability Rules",
          "Bayes Theorem",
          "Random Variables",
          "Probability Distributions",
          "Expected Value",
        ],
      },
      {
        'id': 'inferential',
        'title': 'Inferential Statistics',
        'tier': 'free',
        'topics': [
          "Sampling Methods",
          "Confidence Intervals",
          "Central Limit Theorem",
          "Estimation Theory",
        ],
      },
      {
        'id': 'hypothesis',
        'title': 'Hypothesis Testing',
        'tier': 'free',
        'topics': [
          "Null Hypothesis",
          "Alternative Hypothesis",
          "p-values",
          "Type I/II Errors",
          "Test Selection",
        ],
      },
      {
        'id': 'regression_stats',
        'title': 'Statistical Regression',
        'tier': 'vip',
        'topics': [
          "Linear Regression",
          "Logistic Regression",
          "Model Assumptions",
          "Residual Analysis",
          "Goodness of Fit",
        ],
      },
      {
        'id': 'multivariate',
        'title': 'Multivariate Analysis',
        'tier': 'vip',
        'topics': [
          "Principal Component Analysis",
          "Factor Analysis",
          "Cluster Analysis",
          "Discriminant Analysis",
        ],
      },
      {
        'id': 'time_series_stats',
        'title': 'Time Series Analysis',
        'tier': 'vip',
        'topics': [
          "Trend Analysis",
          "Seasonality",
          "Stationarity",
          "ARIMA Models",
          "Forecasting Methods",
        ],
      },
    ],
    "Business Analytics": [
      {
        'id': 'ba_intro',
        'title': 'Introduction to Business Analytics',
        'tier': 'free',
        'topics': [
          "Business Intelligence vs Analytics",
          "Analytics Maturity Model",
          "Business Value of Analytics",
        ],
      },
      {
        'id': 'kpi',
        'title': 'KPIs and Metrics',
        'tier': 'free',
        'topics': [
          "Key Performance Indicators",
          "Metrics Framework",
          "Benchmarking",
          "Performance Measurement",
        ],
      },
      {
        'id': 'dashboard',
        'title': 'Business Dashboards',
        'tier': 'free',
        'topics': [
          "Dashboard Design Principles",
          "KPI Dashboards",
          "Executive Dashboards",
          "Operational Dashboards",
        ],
      },
      {
        'id': 'roi',
        'title': 'ROI Analysis',
        'tier': 'free',
        'topics': [
          "Cost-Benefit Analysis",
          "Value Measurement",
          "Business Case Development",
          "ROI Calculation",
        ],
      },
      {
        'id': 'forecasting',
        'title': 'Business Forecasting',
        'tier': 'vip',
        'topics': [
          "Demand Forecasting",
          "Sales Forecasting",
          "Financial Forecasting",
          "Scenario Analysis",
        ],
      },
      {
        'id': 'optimization',
        'title': 'Business Optimization',
        'tier': 'vip',
        'topics': [
          "Linear Programming",
          "Resource Allocation",
          "Supply Chain Optimization",
          "Portfolio Optimization",
        ],
      },
    ],
    "Data Visualization": [
      {
        'id': 'viz_principles',
        'title': 'Visualization Principles',
        'tier': 'free',
        'topics': [
          "Visual Perception",
          "Color Theory",
          "Chart Integrity",
          "Data-Ink Ratio",
          "Visual Hierarchy",
        ],
      },
      {
        'id': 'chart_types',
        'title': 'Chart Types and Selection',
        'tier': 'free',
        'topics': [
          "Bar Charts",
          "Line Charts",
          "Scatter Plots",
          "Histograms",
          "Box Plots",
          "Heat Maps",
          "Choosing Right Chart",
        ],
      },
      {
        'id': 'dashboard_design',
        'title': 'Dashboard Design',
        'tier': 'free',
        'topics': [
          "Layout Design",
          "Interactivity",
          "User Experience",
          "Mobile Dashboards",
          "Real-time Dashboards",
        ],
      },
      {
        'id': 'interactive_viz',
        'title': 'Interactive Visualizations',
        'tier': 'free',
        'topics': [
          "Drill-down Capabilities",
          "Filters and Parameters",
          "Dynamic Charts",
          "Web-based Visualizations",
        ],
      },
      {
        'id': 'storytelling',
        'title': 'Data Storytelling',
        'tier': 'vip',
        'topics': [
          "Narrative Structure",
          "Audience Analysis",
          "Presentation Skills",
          "Actionable Insights",
        ],
      },
      {
        'id': 'bi_tools',
        'title': 'BI Tools Mastery',
        'tier': 'vip',
        'topics': [
          "Tool Comparison",
          "Advanced Features",
          "Integration Capabilities",
          "Performance Optimization",
        ],
      },
    ],
    "Data Analysis Tools": [
      {
        'id': 'excel',
        'title': 'Advanced Excel',
        'tier': 'free',
        'topics': [
          "Pivot Tables",
          "Advanced Formulas",
          "Data Validation",
          "Macros",
          "Power Query",
        ],
      },
      {
        'id': 'sql_analytics',
        'title': 'SQL for Analytics',
        'tier': 'free',
        'topics': [
          "Window Functions",
          "CTEs",
          "Subqueries",
          "Performance Tuning",
          "Analytic Functions",
        ],
      },
      {
        'id': 'powerbi',
        'title': 'Power BI',
        'tier': 'free',
        'topics': [
          "Data Modeling",
          "DAX Formulas",
          "Power Query M",
          "Report Development",
          "Service Administration",
        ],
      },
      {
        'id': 'tableau',
        'title': 'Tableau',
        'tier': 'vip',
        'topics': [
          "Calculated Fields",
          "Parameters",
          "Level of Detail Expressions",
          "Dashboard Actions",
          "Data Blending",
        ],
      },
      {
        'id': 'looker',
        'title': 'Looker Studio',
        'tier': 'vip',
        'topics': [
          "LookML Modeling",
          "Explores",
          "Dashboards",
          "Liquid Templates",
          "Git Integration",
        ],
      },
      {
        'id': 'qlik',
        'title': 'Qlik Sense',
        'tier': 'vip',
        'topics': [
          "Associative Engine",
          "Data Modeling",
          "Set Analysis",
          "Scripting",
          "Extensions",
        ],
      },
    ],
    "Machine Learning": [
      {
        'id': 'basic',
        'title': 'Basics',
        'tier': 'free',
        'topics': [
          "Definition and Types",
          "Applications and Workflow",
          "Key Terminology",
        ],
      },
      {
        'id': 'preprocess',
        'title': 'Data Preprocessing',
        'tier': 'free',
        'topics': [
          "Data Cleaning and Feature Scaling",
          "Encoding Categorical Variables",
          "Data Splitting",
        ],
      },
      {
        'id': 'supervise',
        'title': 'Supervised Learning',
        'tier': 'free',
        'topics': [
          "Regression and Classification",
          "Ensemble Methods",
          "Evaluation Metrics",
        ],
      },
      {
        'id': 'unsupervise',
        'title': 'Unsupervised Learning',
        'tier': 'free',
        'topics': [
          "Clustering",
          "Dimensionality Reduction",
          "Anomaly Detection",
        ],
      },
      {
        'id': 'dl',
        'title': 'Deep Learning',
        'tier': 'vip',
        'topics': [
          "Neural Networks and Activation Functions",
          "CNNs and RNNs for Images and Sequences",
          "Training Methods",
        ],
      },
      {
        'id': 'eval',
        'title': 'Model Evaluation and Validation',
        'tier': 'vip',
        'topics': [
          "Cross-Validation and Hyperparameter Tuning",
          "Overfitting and Underfitting",
          "Evaluation Metrics",
        ],
      },
      {
        'id': 'nlp',
        'title': 'Natural Language Processing (NLP)',
        'tier': 'vip',
        'topics': [
          "Text Preprocessing and Vectorization",
          "NLP Models",
          "Applications",
        ],
      },
      {
        'id': 'deploy',
        'title': 'Model Deployment',
        'tier': 'vip',
        'topics': ["Model Serialization", "APIs", "Cloud Deployment"],
      },
    ],
    "Deep Learning": [
      {
        'id': 'dl_intro',
        'title': 'Neural Networks Basics',
        'tier': 'free',
        'topics': [
          "Neural Network Architecture",
          "Activation Functions",
          "Backpropagation",
          "Optimization Algorithms",
        ],
      },
      {
        'id': 'cnn',
        'title': 'Convolutional Neural Networks',
        'tier': 'free',
        'topics': [
          "Convolutional Layers",
          "Pooling",
          "CNN Architectures",
          "Transfer Learning",
          "Object Detection",
        ],
      },
      {
        'id': 'rnn',
        'title': 'Recurrent Neural Networks',
        'tier': 'free',
        'topics': [
          "LSTM",
          "GRU",
          "Sequence Modeling",
          "Time Series Prediction",
          "Text Generation",
        ],
      },
      {
        'id': 'nlp_dl',
        'title': 'NLP with Deep Learning',
        'tier': 'free',
        'topics': [
          "Word Embeddings",
          "Sequence-to-Sequence Models",
          "Attention Mechanism",
          "BERT",
          "GPT Models",
        ],
      },
      {
        'id': 'computer_vision',
        'title': 'Computer Vision',
        'tier': 'vip',
        'topics': [
          "Image Classification",
          "Object Detection",
          "Semantic Segmentation",
          "Image Generation",
        ],
      },
      {
        'id': 'transformers',
        'title': 'Transformer Models',
        'tier': 'vip',
        'topics': [
          "Transformer Architecture",
          "Self-Attention",
          "BERT Applications",
          "GPT Applications",
          "Fine-tuning",
        ],
      },
    ],
    "AI Applications": [
      {
        'id': 'recommender',
        'title': 'Recommendation Systems',
        'tier': 'free',
        'topics': [
          "Collaborative Filtering",
          "Content-Based Filtering",
          "Hybrid Methods",
          "Evaluation Metrics",
        ],
      },
      {
        'id': 'anomaly',
        'title': 'Anomaly Detection',
        'tier': 'free',
        'topics': [
          "Statistical Methods",
          "Machine Learning Approaches",
          "Real-time Detection",
          "Root Cause Analysis",
        ],
      },
      {
        'id': 'computer_vision_app',
        'title': 'Computer Vision Applications',
        'tier': 'free',
        'topics': [
          "Image Recognition",
          "Object Detection",
          "Facial Recognition",
          "Medical Imaging",
        ],
      },
      {
        'id': 'nlp_app',
        'title': 'NLP Applications',
        'tier': 'vip',
        'topics': [
          "Sentiment Analysis",
          "Text Classification",
          "Named Entity Recognition",
          "Chatbots",
          "Translation",
        ],
      },
      {
        'id': 'time_series_ml',
        'title': 'Time Series Forecasting',
        'tier': 'vip',
        'topics': [
          "LSTM for Forecasting",
          "Prophet",
          "ARIMA with ML",
          "Multivariate Time Series",
        ],
      },
    ],
    "Big Data Tools": [
      {
        'id': 'hadoop',
        'title': 'Hadoop Ecosystem',
        'tier': 'free',
        'topics': [
          "HDFS",
          "MapReduce",
          "YARN",
          "Hadoop Architecture",
          "Ecosystem Components",
        ],
      },
      {
        'id': 'spark',
        'title': 'Apache Spark',
        'tier': 'free',
        'topics': [
          "RDDs",
          "DataFrames",
          "Spark SQL",
          "Streaming",
          "MLlib",
          "Performance Tuning",
        ],
      },
      {
        'id': 'kafka',
        'title': 'Apache Kafka',
        'tier': 'free',
        'topics': [
          "Pub-Sub Model",
          "Topics and Partitions",
          "Producers and Consumers",
          "Stream Processing",
        ],
      },
      {
        'id': 'hive',
        'title': 'Apache Hive',
        'tier': 'vip',
        'topics': [
          "HiveQL",
          "Partitioning",
          "Bucketing",
          "External Tables",
          "Performance Optimization",
        ],
      },
      {
        'id': 'bigquery',
        'title': 'Google BigQuery',
        'tier': 'vip',
        'topics': [
          "BigQuery Architecture",
          "SQL Dialect",
          "Partitioning and Clustering",
          "Cost Optimization",
        ],
      },
    ],
    "Data Engineering": [
      {
        'id': 'etl',
        'title': 'ETL Processes',
        'tier': 'free',
        'topics': [
          "Extraction Methods",
          "Transformation Logic",
          "Loading Strategies",
          "Incremental ETL",
          "Data Validation",
        ],
      },
      {
        'id': 'data_pipelines',
        'title': 'Data Pipelines',
        'tier': 'free',
        'topics': [
          "Pipeline Design",
          "Orchestration",
          "Monitoring",
          "Error Handling",
          "Data Lineage",
        ],
      },
      {
        'id': 'data_quality',
        'title': 'Data Quality Management',
        'tier': 'free',
        'topics': [
          "Data Profiling",
          "Cleaning Rules",
          "Validation Rules",
          "Quality Metrics",
          "Monitoring",
        ],
      },
      {
        'id': 'data_governance',
        'title': 'Data Governance',
        'tier': 'vip',
        'topics': [
          "Data Catalog",
          "Metadata Management",
          "Compliance",
          "Security",
          "Access Control",
        ],
      },
      {
        'id': 'airflow',
        'title': 'Apache Airflow',
        'tier': 'vip',
        'topics': [
          "DAGs",
          "Operators",
          "Sensors",
          "Hooks",
          "Custom Operators",
          "Scaling",
        ],
      },
    ],
    "Databases": [
      {
        'id': 'sql_basics',
        'title': 'SQL Fundamentals',
        'tier': 'free',
        'topics': [
          "SQL Syntax",
          "Joins",
          "Aggregations",
          "Subqueries",
          "Data Types",
          "Constraints",
        ],
      },
      {
        'id': 'nosql',
        'title': 'NoSQL Databases',
        'tier': 'free',
        'topics': [
          "Document Databases",
          "Key-Value Stores",
          "Column Family",
          "Graph Databases",
          "Use Cases",
        ],
      },
      {
        'id': 'query_optimization',
        'title': 'Query Optimization',
        'tier': 'vip',
        'topics': [
          "Query Execution Plans",
          "Indexing Strategies",
          "Partitioning",
          "Caching",
          "Connection Pooling",
        ],
      },
      {
        'id': 'data_modeling',
        'title': 'Data Modeling',
        'tier': 'vip',
        'topics': [
          "ER Diagrams",
          "Normalization",
          "Denormalization",
          "Schema Design",
          "Data Integrity",
        ],
      },
      {
        'id': 'transaction',
        'title': 'Transaction Management',
        'tier': 'vip',
        'topics': [
          "ACID Properties",
          "Isolation Levels",
          "Locking Mechanisms",
          "Concurrency Control",
          "Recovery",
        ],
      },
    ],
    "Data Warehousing": [
      {
        'id': 'warehouse_concepts',
        'title': 'Data Warehouse Concepts',
        'tier': 'free',
        'topics': [
          "OLTP vs OLAP",
          "Data Marts",
          "ETL Processes",
          "Architecture Patterns",
          "Cloud vs On-premise",
        ],
      },
      {
        'id': 'dimensional_modeling',
        'title': 'Dimensional Modeling',
        'tier': 'free',
        'topics': [
          "Star Schema",
          "Snowflake Schema",
          "Fact Tables",
          "Dimension Tables",
          "Slowly Changing Dimensions",
        ],
      },
      {
        'id': 'snowflake',
        'title': 'Snowflake Schema',
        'tier': 'free',
        'topics': [
          "Snowflake Architecture",
          "Virtual Warehouses",
          "Data Sharing",
          "Time Travel",
          "Security Features",
        ],
      },
      {
        'id': 'elt',
        'title': 'ELT Processes',
        'tier': 'vip',
        'topics': [
          "ELT vs ETL",
          "Data Lake Integration",
          "Modern Data Stack",
          "Orchestration Tools",
        ],
      },
      {
        'id': 'cloud_warehouse',
        'title': 'Cloud Data Warehousing',
        'tier': 'vip',
        'topics': [
          "Redshift",
          "BigQuery",
          "Snowflake",
          "Synapse",
          "Cost Management",
          "Performance Optimization",
        ],
      },
    ],
    "Programming Languages": [
      {
        'id': 'python_ds',
        'title': 'Python for Data Science',
        'tier': 'free',
        'topics': [
          "Python Basics",
          "Data Structures",
          "Libraries Overview",
          "Jupyter Notebooks",
          "Development Environment",
        ],
      },
      {
        'id': 'r_language',
        'title': 'R Programming',
        'tier': 'free',
        'topics': [
          "R Basics",
          "Data Frames",
          "dplyr",
          "ggplot2",
          "R Markdown",
          "Shiny Apps",
        ],
      },
      {
        'id': 'sql_advanced',
        'title': 'Advanced SQL',
        'tier': 'vip',
        'topics': [
          "Window Functions",
          "Recursive Queries",
          "Dynamic SQL",
          "Query Optimization",
          "PL/SQL",
        ],
      },
      {
        'id': 'scala',
        'title': 'Scala for Big Data',
        'tier': 'vip',
        'topics': [
          "Scala Basics",
          "Functional Programming",
          "Spark with Scala",
          "Type System",
          "Collections",
        ],
      },
    ],
    "Data Science Libraries": [
      {
        'id': 'pandas',
        'title': 'Pandas',
        'tier': 'free',
        'topics': [
          "DataFrames",
          "Series",
          "Data Manipulation",
          "Grouping Operations",
          "Time Series Handling",
        ],
      },
      {
        'id': 'numpy',
        'title': 'NumPy',
        'tier': 'free',
        'topics': [
          "Arrays",
          "Mathematical Operations",
          "Broadcasting",
          "Linear Algebra",
          "Random Number Generation",
        ],
      },
      {
        'id': 'scikit',
        'title': 'Scikit-learn',
        'tier': 'free',
        'topics': [
          "Preprocessing",
          "Model Selection",
          "Evaluation Metrics",
          "Pipelines",
          "Feature Selection",
        ],
      },
      {
        'id': 'matplotlib',
        'title': 'Matplotlib & Seaborn',
        'tier': 'free',
        'topics': [
          "Plot Types",
          "Customization",
          "Statistical Plots",
          "Interactive Plots",
          "Publication Quality",
        ],
      },
      {
        'id': 'tensorflow',
        'title': 'TensorFlow',
        'tier': 'vip',
        'topics': [
          "Keras API",
          "Neural Networks",
          "Custom Layers",
          "Distributed Training",
          "TensorBoard",
        ],
      },
      {
        'id': 'pytorch',
        'title': 'PyTorch',
        'tier': 'vip',
        'topics': [
          "Dynamic Computation",
          "Autograd",
          "Neural Networks",
          "Transfer Learning",
          "Model Deployment",
        ],
      },
      {
        'id': 'spark_python',
        'title': 'PySpark',
        'tier': 'vip',
        'topics': [
          "Spark DataFrames",
          "MLlib",
          "Streaming",
          "Cluster Computing",
          "Performance Optimization",
        ],
      },
    ],
    "Industry Applications": [
      {
        'id': 'finance',
        'title': 'Financial Analytics',
        'tier': 'free',
        'topics': [
          "Risk Modeling",
          "Fraud Detection",
          "Algorithmic Trading",
          "Credit Scoring",
          "Portfolio Management",
        ],
      },
      {
        'id': 'healthcare',
        'title': 'Healthcare Analytics',
        'tier': 'free',
        'topics': [
          "Patient Analytics",
          "Drug Discovery",
          "Medical Imaging",
          "Clinical Trials",
          "Healthcare Operations",
        ],
      },
      {
        'id': 'retail',
        'title': 'Retail Analytics',
        'tier': 'free',
        'topics': [
          "Customer Analytics",
          "Inventory Optimization",
          "Price Optimization",
          "Market Basket Analysis",
          "Supply Chain",
        ],
      },
      {
        'id': 'marketing',
        'title': 'Marketing Analytics',
        'tier': 'vip',
        'topics': [
          "Customer Segmentation",
          "Campaign Analysis",
          "Channel Attribution",
          "Lifetime Value",
          "A/B Testing",
        ],
      },
      {
        'id': 'supply_chain',
        'title': 'Supply Chain Analytics',
        'tier': 'vip',
        'topics': [
          "Demand Forecasting",
          "Inventory Management",
          "Logistics Optimization",
          "Supplier Analytics",
          "Risk Management",
        ],
      },
    ],
    "Advanced Analytics": [
      {
        'id': 'prescriptive',
        'title': 'Prescriptive Analytics',
        'tier': 'free',
        'topics': [
          "Optimization Models",
          "Simulation",
          "Decision Analysis",
          "What-if Analysis",
          "Scenario Planning",
        ],
      },
      {
        'id': 'optimization_advanced',
        'title': 'Advanced Optimization',
        'tier': 'free',
        'topics': [
          "Linear Programming",
          "Integer Programming",
          "Non-linear Optimization",
          "Heuristic Methods",
          "Multi-objective",
        ],
      },
      {
        'id': 'simulation',
        'title': 'Simulation Modeling',
        'tier': 'free',
        'topics': [
          "Monte Carlo Methods",
          "Discrete Event Simulation",
          "Agent-based Modeling",
          "System Dynamics",
          "Risk Analysis",
        ],
      },
      {
        'id': 'causal_inference',
        'title': 'Causal Inference',
        'tier': 'vip',
        'topics': [
          "Randomized Experiments",
          "Observational Studies",
          "Instrumental Variables",
          "Regression Discontinuity",
          "Matching Methods",
        ],
      },
      {
        'id': 'experimental_design',
        'title': 'Experimental Design',
        'tier': 'vip',
        'topics': [
          "Factorial Designs",
          "Response Surface Methodology",
          "Blocking",
          "Randomization",
          "Sample Size Determination",
        ],
      },
    ],
  };
}
